version: '3'

volumes:
  mysql-data:
    driver: local

services:
  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cakephp:/var/www/cakephp:delegated
      - ./docker/nginx/openssl:/var/www/openssl
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./cakephp:/var/www/cakephp:delegated
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql/etc-mysql.cnf:/etc/mysql/conf.d/etc-mysql.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
