version: '3'

volumes:
  mysql-data:
    driver: local

services:
  nginx:
    image: nginx:1.20-alpine
    container_name: cakephp_debug_sample_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./projects:/var/www/projects:cached
      - ./docker/nginx/openssl:/var/www/openssl
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    env_file:
      - .env

  php-fpm:
    build: ./docker/php-fpm
    container_name: cakephp_debug_sample_php-fpm
    volumes:
      - .:/var/www:cached
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/xdebug.ini
    links:
      - mysql
    env_file:
      - .env

  mysql:
    build: ./docker/mysql
    container_name: cakephp_debug_sample_mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql:/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
