name: CI

on:
  push:
    branches:
      - "*"

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        run: |
          cd cakephp
          cp config/app_local.example.php config/app_local.php
          cp config/.env.example config/.env
      - name: Docker Run
        shell: bash
        run: |
          docker-compose up -d
      - name: Composer install
        run: |
          docker exec cakephp_debug_sample_php-fpm_1 bash -c "cd /var/www/cakephp && composer run-script post-install-cmd --no-interaction"
      - name: Run PHPUnit
        run: |
          docker exec cakephp_debug_sample_php-fpm_1 bash -c "cd /var/www/cakephp && composer test"

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        run: |
          cd cakephp
          cp config/app_local.example.php config/app_local.php
          cp config/.env.example config/.env
      - name: Docker Run
        shell: bash
        run: |
          docker-compose up -d
      - name: Composer install
        run: |
          docker exec cakephp_debug_sample_php-fpm_1 bash -c "cd /var/www/cakephp && composer run-script post-install-cmd --no-interaction"
      - name: Run PHP CodeSniffer
        run: |
          docker exec cakephp_debug_sample_php-fpm_1 bash -c "cd /var/www/cakephp && composer cs-check"

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        run: |
          cd cakephp
          cp config/app_local.example.php config/app_local.php
          cp config/.env.example config/.env
      - name: Docker Run
        shell: bash
        run: |
          docker-compose up -d
      - name: Composer install
        run: |
          docker exec cakephp_debug_sample_php-fpm_1 bash -c "cd /var/www/cakephp && composer run-script post-install-cmd --no-interaction"
      - name: Run phpstan
        run: |
          docker exec cakephp_debug_sample_php-fpm_1 bash -c "cd /var/www/cakephp && vendor/bin/phpstan"
