name: CI

on:
  push:
    branches:
      - "*"

jobs:
  testsuite:
    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: xxxxxxxxxx
          MYSQL_DATABASE: xxxxxxxxxx
          MYSQL_USER: xxxxxxxxxx
          MYSQL_PASSWORD: xxxxxxxxxx
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10

    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.2", "7.4", "8.0", "8.1"]
    name: PHP ${{ matrix.php-version }}

    steps:
      - uses: actions/checkout@v2
        with:
          path: cakephp

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, simplexml, pdo_mysql
          coverage: none

      - name: Composer install
        run: |
          if [[ ${{ matrix.php-version }} == '8.1' ]]; then
            composer update --ignore-platform-reqs
          else
            composer update
          fi
          composer run-script post-install-cmd --no-interaction

      - name: Run PHPUnit
        run: |
          cp config/app_local.example.php config/app_local.php
          cp config/.env.example config/.env
          vendor/bin/phpunit

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          path: cakephp

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.2"
          extensions: mbstring, intl, simplexml, pdo_mysql
          coverage: none

      - name: Composer install
        run: composer install

      - name: Run PHP CodeSniffer
        run: composer cs-check

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          path: cakephp

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.2"
          extensions: mbstring, intl, simplexml, pdo_mysql
          coverage: none

      - name: Composer install
        run: composer require --dev phpstan/phpstan:^1.0.0

      - name: Run phpstan
        run: vendor/bin/phpstan
